image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: tailscaled
    command: |
        if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
          # restore the tailscale state from gitpod user's env vars
          sudo mkdir -p /var/lib/tailscale
          echo "${TAILSCALE_STATE_MYPROJECT}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
        fi
        sudo tailscaled
  - name: tailscale
    command: |
        if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
          sudo -E tailscale up
        else
          sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
          # store the tailscale state into gitpod user
          gp env TAILSCALE_STATE_MYPROJECT="$(sudo cat /var/lib/tailscale/tailscaled.state)"
        fi

#- name: gcloud
#  command: |
#    echo $GCP_ACCOUNT > /home/gitpod/account.json
#    gcloud auth activate-service-account --key-file=/home/gitpod/account.json
#    rm /home/gitpod/account.json
#    gcloud config set project gke-playground-191013
#    gcloud container clusters get-credentials moritz-pet-clinic --zone us-west1-b --project gke-playground-191013
#    kubectl apply -f docker-engine.k8s.yaml
#    kubectl port-forward deployment/docker-engine 2375:2375 &
#    docker login --username meysholdt --password $DOCKER_HUB_TOKEN
#vscode:
#  extensions:
#    - Pivotal.vscode-spring-boot@1.11.0:gKokcVIlbvXM5pr9HCsGiA==
#    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
#    - vscjava.vscode-spring-boot-dashboard@0.1.6:/G6fobfzYSrYZdNU7UB78g==
#    - ms-kubernetes-tools.vscode-kubernetes-tools@1.0.4:Xhg4EprIGTB3Rd2PNCL/xA==
#    - bajdzis.vscode-database@2.2.0:KaEYYfe8G3NOWlsM6VNLHA==

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - yzhang.markdown-all-in-one
